import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "HTML",
      items: [{ type: "autogenerated", dirName: "html" }],
    },
    {
      type: "category",
      label: "CSS",
      items: [{ type: "autogenerated", dirName: "css" }],
    },
    {
      type: "category",
      label: "Javascript",
      items: [{ type: "autogenerated", dirName: "js" }],
    },
    {
      type: "category",
      label: "React",
      items: [{ type: "autogenerated", dirName: "react" }],
    },
    {
      type: "category",
      label: "Next.js",
      items: [{ type: "autogenerated", dirName: "next" }],
    },
    {
      type: "category",
      label: "Vue",
      items: [{ type: "autogenerated", dirName: "vue" }],
    },
    {
      type: "category",
      label: "Git",
      items: [{ type: "autogenerated", dirName: "git" }],
    },
    {
      type: "category",
      label: "Network",
      items: [{ type: "autogenerated", dirName: "network" }],
    },
    {
      type: "category",
      label: "DSA",
      items: [{ type: "autogenerated", dirName: "dsa" }],
    },
    {
      type: "category",
      label: "Technical",
      items: [{ type: "autogenerated", dirName: "technical" }],
    },
    {
      type: "category",
      label: "CI / CD",
      items: [{ type: "autogenerated", dirName: "ci-cd" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
